### ISSUE TITLE
PMD fails on UseStringIsEmptyRule in RandomizedTest.java

### ISSUE THREAD

**Issue by vzurauskas** [yegor256/cactoos#1110]
See the latest build: http://www.rultor.com/t/18634-484857176

```
Apr 19, 2019 11:31:00 AM net.sourceforge.pmd.RuleSet apply
WARNING: Exception applying rule UseStringIsEmptyRule on file /home/r/repo/src/test/java/org/cactoos/text/RandomizedTest.java, continuing with next rule
java.lang.NullPointerException
        at com.qulice.pmd.rules.UseStringIsEmptyRule.visit(UseStringIsEmptyRule.java:101)
        at net.sourceforge.pmd.lang.java.ast.ASTPrimarySuffix.jjtAccept(ASTPrimarySuffix.java:55)
        at net.sourceforge.pmd.lang.java.ast.AbstractJavaNode.childrenAccept(AbstractJavaNode.java:55)
        at net.sourceforge.pmd.lang.java.rule.AbstractJavaRule.visit(AbstractJavaRule.java:74)
        at net.sourceforge.pmd.lang.java.rule.AbstractJavaRule.visit(AbstractJavaRule.java:375)
        . . .
```

The build still passes, but the `UseStringIsEmptyRule` is failing, so it should be fixed.

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue

**Comment by vzurauskas** [comment]
Actually, it's a dublicate. Will be resolved by https://github.com/teamed/qulice/issues/1033.

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#1110` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
