### ISSUE TITLE
IterableOf.equals is broken

### ISSUE THREAD

**Issue by victornoel** [yegor256/cactoos#1308]
Running the following test:
```java
    @Test
    public void test() {
        new Assertion<>(
            "Must compare iterables of different lengths",
            new IterableOf<>("a", "b").equals(new IterableOf<>("a")),
            new IsNot<>(new IsTrue())
        ).affirm();
    }
```

Throws the following exception:
```
java.util.NoSuchElementException: The iterator doesn't have any more items
	at org.cactoos.iterator.IteratorOf.next(IteratorOf.java:68)
	at org.cactoos.iterable.IterableOf.lambda$8(IterableOf.java:161)
	at org.cactoos.scalar.And.lambda$1(And.java:94)
	at org.cactoos.scalar.And.value(And.java:137)
	at org.cactoos.scalar.And.value(And.java:1)
	at org.cactoos.scalar.Checked.value(Checked.java:76)
	at org.cactoos.scalar.IoChecked.value(IoChecked.java:63)
	at org.cactoos.scalar.Unchecked.value(Unchecked.java:56)
	at org.cactoos.iterable.IterableOf.lambda$7(IterableOf.java:164)
	at org.cactoos.scalar.And.value(And.java:137)
	at org.cactoos.scalar.And.value(And.java:1)
	at org.cactoos.scalar.Or.value(Or.java:170)
	at org.cactoos.scalar.Or.value(Or.java:1)
	at org.cactoos.scalar.Checked.value(Checked.java:76)
	at org.cactoos.scalar.IoChecked.value(IoChecked.java:63)
	at org.cactoos.scalar.Unchecked.value(Unchecked.java:56)
	at org.cactoos.iterable.IterableOf.equals(IterableOf.java:168)
	at org.cactoos.iterable.IterableOfTest.test(IterableOfTest.java:122)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:89)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:41)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:542)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:770)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:464)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)
```

I believe the test should simply pass.

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) please, pay attention to this issue

**Comment by paulodamaso** [comment]
@0crat in

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @victornoel[/z](https://www.0crat.com/u/victornoel)

**Comment by 0crat** [comment]
The job [#1308](https://github.com/yegor256/cactoos/issues/1308) assigned to @iiylll[/z](https://www.0crat.com/u/iiylll), here is [why](https://www.0crat.com/footprint/C63314D6Z/1e98cfd9-be87-417e-bb78-ac85cbb9a3a0); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by victornoel** [comment]
@lxpdd you should have notified me so that I can close the issue, lucky I passed by it by chance :)

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @iiylll[/z](https://www.0crat.com/u/iiylll), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by sereshqua** [comment]
@0crat quality good
