### ISSUE TITLE
cactoos 0.45 fails to compile/execute tests on OpenJDK 11

### ISSUE THREAD

**Issue by fabriciofx** [yegor256/cactoos#1415]
Cactoos fails to compile/execute tests on OpenJDK 14.0.1. @victornoel WDYT?

1. Info
```
fbc@nyx$ javac -version
javac 14.0.1
fbc@nyx$ java -version
openjdk version "14.0.1" 2020-04-14
OpenJDK Runtime Environment (build 14.0.1+7-Ubuntu-1ubuntu1)
OpenJDK 64-Bit Server VM (build 14.0.1+7-Ubuntu-1ubuntu1, mixed mode, sharing)
```
2. Error message
```
[INFO] --- maven-compiler-plugin:3.8.0:testCompile (default-testCompile) @ cactoos ---
[INFO] Compiling 274 source files to /mnt/c/Users/fbc/code/yegor256/cactoos/target/test-classes
[INFO]
[INFO] --- maven-surefire-plugin:2.19.1:test (default-test) @ cactoos ---

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Exceptioat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:513)
        at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:525)
Caused by: java.lang.RuntimeException: Class java/lang/UnknownError could not be instrumented.
        at org.jacoco.agent.rt.internal_290345e.core.runtime.ModifiedSystemClassRuntime.createFor(ModifiedSystemClassRuntime.java:139)
        at org.jacoco.agent.rt.internal_290345e.core.runtime.ModifiedSystemClassRuntime.createFor(ModifiedSystemClassRuntime.java:100)
        at org.jacoco.agent.rt.internal_290345e.PreMain.createRuntime(PreMain.java:55)
        at org.jacoco.agent.rt.internal_290345e.PreMain.premain(PreMain.java:47)
        ... 6 more
Caused by: java.lang.NoSuchFieldException: $jacocoAccess
        at java.base/java.lang.Class.getField(Class.java:2013)
        at org.jacoco.agent.rt.internal_290345e.core.runtime.ModifiedSystemClassRuntime.createFor(ModifiedSystemClassRuntime.java:137)
        ... 9 more
*** java.lang.instrument ASSERTION FAILED ***: "result" with message agent load/premain call failed at src/java.instrument/share/native/libinstrument/JPLISAgent.c line: 422
FATAL ERROR in native method: processing of -javaagent failed, processJavaStart failed
Aborted

Results :

Tests run: 0, Failures: 0, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  02:00 min
[INFO] Finished at: 2020-07-05T20:25:26-03:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test (default-test) on project cactoos: Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test failed: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
[ERROR] Command was /bin/sh -c cd /mnt/c/Users/fbc/code/yegor256/cactoos && /usr/lib/jvm/java-14-openjdk-amd64/bin/java -javaagent:/mnt/c/Users/fbc/.m2/repository/org/jacoco/org.jacoco.agent/0.8.0/org.jacoco.agent-0.8.0-runtime.jar=destfile=/mnt/c/Users/fbc/code/yegor256/cactoos/target/jacoco.exec,output=file -jar /mnt/c/Users/fbc/code/yegor256/cactoos/target/surefire/surefirebooter16577817682501782832.jar /mnt/c/Users/fbc/code/yegor256/cactoos/target/surefire/surefire16892051813673841269tmp /mnt/c/Users/fbc/code/yegor256/cactoos/target/surefire/surefire_07684830434987015199tmp
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
```

**Comment by 0crat** [comment]
@victornoel[/z](https://www.0crat.com/u/victornoel) please, pay attention to this issue

**Comment by victornoel** [comment]
@fabriciofx let's wait for #1417 before tackling that. Maybe we will first focus on jdk11, because jdk14 is not an LTS.

**Comment by fabriciofx** [comment]
@victornoel I agree. I also think #1417 can solve this problem.

**Comment by andreoss** [comment]
@fabriciofx @victornoel 
As for now, 11 and 14 compile and run tests just fine. 
But qulice does not support 11 yet https://github.com/teamed/qulice/issues/878, so `-Pquice` won't work

**Comment by victornoel** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/yegor256/cactoos/issues/1415#issuecomment-719962912))

@victornoel This is what I know about this job in C63314D6Z, as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#1415](https://github.com/yegor256/cactoos/issues/1415) is not in scope
  * Job [footprint](https://www.0crat.com/footprint/C63314D6Z?q=%7Bjob%3A%27gh%3Ayegor256%2Fcactoos%231415%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by victornoel** [comment]
@0crat assign @andreoss

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @andreoss[/z](https://www.0crat.com/u/andreoss), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by sereshqua** [comment]
@0crat quality good

**Comment by sereshqua** [comment]
@0crat quality good

**Comment by 0crat** [comment]
> @0crat quality good ([here](https://github.com/yegor256/cactoos/issues/1415#issuecomment-723565120))

@sereshqua There is no quality review for [#1415](https://github.com/yegor256/cactoos/issues/1415), no performer
