### ISSUE TITLE
Base64 Decoder

### ISSUE THREAD

**Issue by memoyil** [yegor256/cactoos#224]
Lets make Base64 Decoder

**Comment by 0crat** [comment]
@memoyil I'm not managing this repo, remove the [webhook](https://github.com/yegor256/cactoos/settings/hooks) or contact me in [Slack](http://www.zerocracy.com) //cc @yegor256

**Comment by memoyil** [comment]
Pullrequest of this issue #223

**Comment by 0crat** [comment]
I can't do it for technical reasons, I'm very sorry. If you don't know what to do, submit this error as a ticket [here](https://github.com/zerocracy/datum):

```
1.0-SNAPSHOT ${buildNumber} 2017-06-29T17:45:24
java.io.IOException: java.lang.IllegalStateException: com.zerocracy.jstk.SoftException: Job `gh:yegor256/cactoos#224` was not in scope
	at org.cactoos.func.IoCheckedFunc.apply(IoCheckedFunc.java:74)
	at com.zerocracy.farm.SmartFarm.lambda$null$5(SmartFarm.java:142)
	at com.zerocracy.farm.StkSafe.process(StkSafe.java:73)
	at com.zerocracy.farm.reactive.Brigade.process(Brigade.java:91)
	at com.zerocracy.farm.reactive.Brigade.process(Brigade.java:67)
	at com.zerocracy.farm.reactive.Spinner.process(Spinner.java:120)
	at com.zerocracy.farm.reactive.Spinner.next(Spinner.java:105)
	at com.zerocracy.farm.reactive.Spinner.process(Spinner.java:81)
	at com.zerocracy.farm.reactive.Spinner.run(Spinner.java:67)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExec...
```
