### ISSUE TITLE
AsciiText

### ISSUE THREAD

**Issue by ixmanuel** [yegor256/cactoos#235]
Transliterate an unicode text to ASCII.
```java
new AsciiText("Ç©mm©ñ").asString(); // Common
```

_It is a requirement to write SluggedText_

**Comment by 0crat** [comment]
@ixmanuel I'm not managing this repo, remove the [webhook](https://github.com/yegor256/cactoos/settings/hooks) or contact me in [Slack](http://www.zerocracy.com) //cc @yegor256

**Comment by 0crat** [comment]
I can't do it for technical reasons, I'm very sorry. If you don't know what to do, submit this error as a ticket [here](https://github.com/zerocracy/datum):

```
1.0-SNAPSHOT ${buildNumber} 2017-08-04T07:36:32
java.lang.IllegalStateException: java.lang.reflect.InvocationTargetException
	at com.zerocracy.farm.reactive.StkGroovy.process(StkGroovy.java:115)
	at com.zerocracy.farm.StkSafe.process(StkSafe.java:89)
	at com.zerocracy.farm.reactive.Brigade.process(Brigade.java:103)
	at com.zerocracy.farm.reactive.Brigade.process(Brigade.java:82)
	at com.zerocracy.farm.reactive.FlushAction.process(FlushAction.java:85)
	at com.zerocracy.farm.reactive.FlushAction.exec(FlushAction.java:67)
	at com.zerocracy.farm.reactive.FlushAction.exec(FlushAction.java:35)
	at org.cactoos.func.FuncOf.lambda$new$3(FuncOf.java:88)
	at org.cactoos.func.FuncOf.apply(FuncOf.java:104)
	at org.cactoos.func.IoCheckedFunc.apply(IoCheckedFunc.java:66)
	at org.cactoos.func.UncheckedFunc.apply(UncheckedFunc.java:59)
	at org.cactoos.func.RunnableOf.run(RunnableOf.java:89)
	at com.jcabi.log.VerboseRunnable.run(VerboseRunnable.java:197)
	at com.zerocracy.farm.reactive.RunnableWithTrigger.run(RunnableWithTrigger.java:52)
	at java....
```
