### ISSUE TITLE
FilteredText

### ISSUE THREAD

**Issue by svendiedrichsen** [yegor256/cactoos#344]
It might be interesting to have a FilteredText to filter out illegal characters. WDYT?

**Comment by 0crat** [comment]
I can't do it for technical reasons, I'm very sorry. If you don't know what to do, submit this error as a ticket [here](https://github.com/zerocracy/datum):

```
1.0-SNAPSHOT f2c623f 2017-08-14T16:18:41
IllegalStateException: java.lang.reflect.InvocationTargetException
com.zerocracy.jstk.SoftException: Job `gh:yegor256/cactoos#344` was not in scope
	at com.zerocracy.pm.scope.Wbs.remove(Wbs.java:107)
	at com.zerocracy.pm.scope.Wbs$remove$3.call(Unknown Source)
	at com.zerocracy.stk.pm.scope.wbs.remove_job_from_wbs.exec(remove_job_from_wbs.groovy:32)
	at sun.reflect.GeneratedMethodAccessor54.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.zerocracy.farm.reactive.StkGroovy.process(StkGroovy.java:109)
	at com.zerocracy.farm.StkSafe.process(StkSafe.java:90)
	at com.zerocracy.farm.reactive.Brigade.process(Brigade.java:105)
	at com.zerocracy.farm.reactive.Brigade.process(Brigade.java:82)
	at com.zerocracy.farm.reactive.FlushAction.process(FlushAction.java:85)
	at com.zerocracy.farm.reactive.FlushAction.exec(FlushAction.java:67)
	at com.zerocracy.farm.reactive.FlushAction.exec(FlushAction.java:35)
	at org.cactoos.func.FuncOf.lambda...
```
