### ISSUE TITLE
Bytes validation like consistsOnlyOf(Bytes b) or LimitedBytesOf/RestrictedBytesOf

### ISSUE THREAD

**Issue by svendiedrichsen** [yegor256/cactoos#349]
As I was looking at PR #225 I thought about some additional functionality for the Bytes interface which allows to answer questions like i.e. consistsOnlyOf(Bytes bytes). The Base64ToInput class implements this for checking if there are any non-base64 bytes in it. 
Or would it be more sensible to have a class LimitedBytesOf with a limiting BytesOf instance?
WDYT?

**Comment by 0crat** [comment]
I can't do it for technical reasons, I'm very sorry. If you don't know what to do, submit this error as a ticket [here](https://github.com/zerocracy/datum):

```
0.15.2 96d4c0a 2017-07-30T06:58:34
java.io.IOException: java.lang.IllegalArgumentException: There are 1 parameter(s) but only 0 format argument(s) were provided.
	at org.cactoos.func.IoCheckedFunc.apply(IoCheckedFunc.java:74)
	at com.zerocracy.farm.SmartFarm.lambda$null$4(SmartFarm.java:137)
	at com.zerocracy.farm.StkSafe.process(StkSafe.java:89)
	at com.zerocracy.farm.reactive.Brigade.process(Brigade.java:103)
	at com.zerocracy.farm.reactive.Brigade.process(Brigade.java:82)
	at com.zerocracy.farm.reactive.FlushAction.process(FlushAction.java:85)
	at com.zerocracy.farm.reactive.FlushAction.exec(FlushAction.java:67)
	at com.zerocracy.farm.reactive.FlushAction.exec(FlushAction.java:35)
	at org.cactoos.func.FuncOf.lambda$new$3(FuncOf.java:88)
	at org.cactoos.func.FuncOf.apply(FuncOf.java:104)
	at org.cactoos.func.IoCheckedFunc.apply(IoCheckedFunc.java:66)
	at org.cactoos.func.UncheckedFunc.apply(UncheckedFunc.java:59)
	at org.cactoos.func.RunnableOf.run(RunnableOf.java:89)
	at com.jcabi.log.VerboseRunnable.run(VerboseRu...
```
