### ISSUE TITLE
Remove Comparable<Text> into Text

### ISSUE THREAD

**Issue by fabriciofx** [yegor256/cactoos#353]
After added support to `Comparable<Text>` into `Text` we lost the advantage to use lambdas with `Text`. Besides, we have [`Equality`](https://github.com/yegor256/cactoos/issues/308) that can performs the same like `Comparable<Text`. So, let's remove `Comparable<Text` support in favor of `Equality`.

@yegor256 @ixmanuel WDYT?

**Comment by ixmanuel** [comment]
@fabriciofx @yegor256 
Yes, we have lost that advantage. I have had to use Scalar<Text>. But, we have some other benefits. I wrote a test for your SubText @fabriciofx because the idea of SubText with CompareTo is "elegant".

**Comment by fabriciofx** [comment]
@ixmanuel @yegor256 We can do the same thing like:
```
new Equality<>(
   new SubText("from here to there", 5),
  new SubText("from here to there", 18)
).value()
```
WDYT?

**Comment by ixmanuel** [comment]
@fabriciofx I really like it.

**Comment by fabriciofx** [comment]
@ixmanuel We already have it implemented in #308, just waiting for merge.

**Comment by ixmanuel** [comment]
The renaming and refactoring is almost done. :)

**Comment by fabriciofx** [comment]
@ixmanuel Yeah, after the code is merged and @yegor256 aproved this issue, I will make a refactoring to remove `compareTo()`.

**Comment by Zefick** [comment]
If I'm not mistaken and understand the issue then `Text` cannot implement `Bytes`. Otherwise it will cause the same problem with lambdas as `Comparable` did.

The solution may be to create `ComparableText` decorator that will implement `Comparable`, `Text`, `Bytes` and whatever you want.

 ```Java
new Equality <>(
    new ComparableText(() -> "here"),
    new ComparableText(new SubText("from here to there", 18))
).value()
```
In case if it will implement `Comparable<Text>` the same code can looks even simplier:

 ```Java
new ComparableText(() -> "here")
    .compareTo(new SubText("from here to there", 18))
```

**Comment by 0crat** [comment]
There is an unrecoverablefailure on my side. Please, submit it [here](https://github.com/zerocracy/datum):

```
java.lang.ClassCastException: org.glassfish.json.JsonObjectBuilderImpl$JsonObjectImpl cannot be cast to javax.json.JsonString
	at org.glassfish.json.JsonObjectBuilderImpl$JsonObjectImpl.getJsonString(JsonObjectBuilderImpl.java:252)
	at org.glassfish.json.JsonObjectBuilderImpl$JsonObjectImpl.getString(JsonObjectBuilderImpl.java:257)
	at com.zerocracy.radars.github.RbByLabel.react(RbByLabel.java:82)
	at com.zerocracy.radars.github.RbByActions.react(RbByActions.java:65)
	at com.zerocracy.radars.github.Rebound$Chain.react(Rebound.java:74)
	at com.zerocracy.radars.github.RbSafe.lambda$react$0(RbSafe.java:63)
	at org.cactoos.func.FuncWithFallback.apply(FuncWithFallback.java:299)
	at org.cactoos.func.IoCheckedFunc.apply(IoCheckedFunc.java:66)
	at com.zerocracy.radars.github.RbSafe.react(RbSafe.java:79)
	at com.zerocracy.radars.github.RbLogged.react(RbLogged.java:52)
	at com.zerocracy.radars.github.TkGithub.act(TkGithub.java:161)
	at org.takes.facets.fork.FkRegex$1.act(FkRegex.java:154)
	at...
```

**Comment by 0crat** [comment]
There is an unrecoverablefailure on my side. Please, submit it [here](https://github.com/zerocracy/datum):

```
java.lang.ClassCastException: org.glassfish.json.JsonObjectBuilderImpl$JsonObjectImpl cannot be cast to javax.json.JsonString
	at org.glassfish.json.JsonObjectBuilderImpl$JsonObjectImpl.getJsonString(JsonObjectBuilderImpl.java:252)
	at org.glassfish.json.JsonObjectBuilderImpl$JsonObjectImpl.getString(JsonObjectBuilderImpl.java:257)
	at com.zerocracy.radars.github.RbByLabel.react(RbByLabel.java:82)
	at com.zerocracy.radars.github.RbByActions.react(RbByActions.java:65)
	at com.zerocracy.radars.github.Rebound$Chain.react(Rebound.java:74)
	at com.zerocracy.radars.github.RbSafe.lambda$react$0(RbSafe.java:63)
	at org.cactoos.func.FuncWithFallback.apply(FuncWithFallback.java:299)
	at org.cactoos.func.IoCheckedFunc.apply(IoCheckedFunc.java:66)
	at com.zerocracy.radars.github.RbSafe.react(RbSafe.java:79)
	at com.zerocracy.radars.github.RbLogged.react(RbLogged.java:52)
	at com.zerocracy.radars.github.TkGithub.act(TkGithub.java:161)
	at org.takes.facets.fork.FkRegex$1.act(FkRegex.java:154)
	at...
```

**Comment by 0crat** [comment]
There is an unrecoverablefailure on my side. Please, submit it [here](https://github.com/zerocracy/datum):

```
java.lang.ClassCastException: org.glassfish.json.JsonObjectBuilderImpl$JsonObjectImpl cannot be cast to javax.json.JsonString
	at org.glassfish.json.JsonObjectBuilderImpl$JsonObjectImpl.getJsonString(JsonObjectBuilderImpl.java:252)
	at org.glassfish.json.JsonObjectBuilderImpl$JsonObjectImpl.getString(JsonObjectBuilderImpl.java:257)
	at com.zerocracy.radars.github.RbByLabel.react(RbByLabel.java:82)
	at com.zerocracy.radars.github.RbByActions.react(RbByActions.java:65)
	at com.zerocracy.radars.github.Rebound$Chain.react(Rebound.java:74)
	at com.zerocracy.radars.github.RbSafe.lambda$react$0(RbSafe.java:63)
	at org.cactoos.func.FuncWithFallback.apply(FuncWithFallback.java:299)
	at org.cactoos.func.IoCheckedFunc.apply(IoCheckedFunc.java:66)
	at com.zerocracy.radars.github.RbSafe.react(RbSafe.java:79)
	at com.zerocracy.radars.github.RbLogged.react(RbLogged.java:52)
	at com.zerocracy.radars.github.TkGithub.act(TkGithub.java:161)
	at org.takes.facets.fork.FkRegex$1.act(FkRegex.java:154)
	at...
```

**Comment by 0crat** [comment]
There is an unrecoverablefailure on my side. Please, submit it [here](https://github.com/zerocracy/datum):

```
java.lang.ClassCastException: org.glassfish.json.JsonObjectBuilderImpl$JsonObjectImpl cannot be cast to javax.json.JsonString
	at org.glassfish.json.JsonObjectBuilderImpl$JsonObjectImpl.getJsonString(JsonObjectBuilderImpl.java:252)
	at org.glassfish.json.JsonObjectBuilderImpl$JsonObjectImpl.getString(JsonObjectBuilderImpl.java:257)
	at com.zerocracy.radars.github.RbByLabel.react(RbByLabel.java:82)
	at com.zerocracy.radars.github.RbByActions.react(RbByActions.java:65)
	at com.zerocracy.radars.github.Rebound$Chain.react(Rebound.java:74)
	at com.zerocracy.radars.github.RbSafe.lambda$react$0(RbSafe.java:63)
	at org.cactoos.func.FuncWithFallback.apply(FuncWithFallback.java:299)
	at org.cactoos.func.IoCheckedFunc.apply(IoCheckedFunc.java:66)
	at com.zerocracy.radars.github.RbSafe.react(RbSafe.java:79)
	at com.zerocracy.radars.github.RbLogged.react(RbLogged.java:52)
	at com.zerocracy.radars.github.TkGithub.act(TkGithub.java:161)
	at org.takes.facets.fork.FkRegex$1.act(FkRegex.java:154)
	at...
```

**Comment by fabriciofx** [comment]
@yegor256 Could you assing this issue to me? Thanks in advance.

**Comment by 0crat** [comment]
Job [#353](https://github.com/yegor256/cactoos/issues/353) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://datum.zerocracy.com/pages/policy.html#29): +15 points just awarded to [@fabriciofx](http://www.0crat.com/u/fabriciofx), total is [+150](http://www.0crat.com/u/fabriciofx)

**Comment by 0crat** [comment]
The job [#353](https://github.com/yegor256/cactoos/issues/353) assigned to icok. The budget is 30 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§8](http://datum.zerocracy.com/pages/policy.html#8) and [§9](http://datum.zerocracy.com/pages/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by 0crat** [comment]
@icok[/z](http://www.0crat.com/u/icok) this job was assigned to you 5 days ago. It will be taken away from you soon, unless you close it, see [§8](http://datum.zerocracy.com/pages/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
@icok[/z](https://www.0crat.com/u/icok) this job was assigned to you 8 days ago. It will be taken away from you soon, unless you close it, see [§8](http://datum.zerocracy.com/pages/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
The user @icok[/z](https://www.0crat.com/u/icok) resigned from [#353](https://github.com/yegor256/cactoos/issues/353), please stop working

**Comment by fabriciofx** [comment]
@yegor256 As this issue was solved by commit [a5efd00f](https://github.com/yegor256/cactoos/commit/a5efd00f), I'll close this issue.

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#353` is not assigned, can't get start time

**Comment by 0crat** [comment]
The job [#353](https://github.com/yegor256/cactoos/issues/353) is now out of scope

**Comment by 0crat** [comment]
Job [#353](https://github.com/yegor256/cactoos/issues/353) was not in scope
