### ISSUE TITLE
RepeatIterable is ambiguous 

### ISSUE THREAD

**Issue by ixmanuel** [yegor256/cactoos#357]
@yegor256, @fabriciofx, @g4s8 
### Case
- RepeatedText.- It doesn’t have double meanings.
- RepeatIterable.- In the programming context it is ambiguous because we have a baggage:
    - Do we want to put together two or more iterables?
    - Is it a loop? While? or For? is it for repeating statements or values?
- EndlessIterable.- Same as above.

### Alternatives
1. We could choose **RepeatedItem** that conforms to the same meaning that **RepeatedText** although it lose the Of suffix and I think it worth it.
    We get symmetry and transitivity: RepeatedItem implies the same meaning as RepeatedText and we can say the same for EndlessItem. Also, we could remove EndlessItem in favour of a new ctor. without params in RepeatedItem.

2. Alternatively, we might choose CopiesOf, RepeatedText and EndlessItem

### Assessment
**Alternative 1**. 
    It has symmetry and transitivity. Nice for remembering and understanding: RepeatedText, RepeatedItem and EndlessItem (if you decide to keep it).
    In context:
```java
CountOf
    RepeatedItem<>
        item
```

**Alternative 2**. It lacks of symmetry and transitivity: CopiesOf, RepeatedText, EndlessItem but not in the context of iterables.
```java
CountOf
    RepeatedOf<>
        item
```

I prefer alternative 1.

Finally, I think we could add an optional separator to the RepeatedText @fabriciofx wdyt?

**Comment by g4s8** [comment]
@ixmanuel I agree - these names could be better. 

> Is it a loop? While? or For?

Here I don't think it's important, because `while` and `for` usage in iterable is implementation detail. As a deveolper I don't care how exactly this sequence implemented.

**Comment by ixmanuel** [comment]
yes, you're right. I let it unchanged.

**Comment by 0crat** [comment]
I can't do it for technical reasons, I'm very sorry. If you don't know what to do, submit this error as a ticket [here](https://github.com/zerocracy/datum):

```
0.15.2 96d4c0a 2017-07-30T06:58:34
java.io.IOException: java.lang.IllegalArgumentException: There are 1 parameter(s) but only 0 format argument(s) were provided.
	at org.cactoos.func.IoCheckedFunc.apply(IoCheckedFunc.java:74)
	at com.zerocracy.farm.SmartFarm.lambda$null$4(SmartFarm.java:137)
	at com.zerocracy.farm.StkSafe.process(StkSafe.java:89)
	at com.zerocracy.farm.reactive.Brigade.process(Brigade.java:103)
	at com.zerocracy.farm.reactive.Brigade.process(Brigade.java:82)
	at com.zerocracy.farm.reactive.FlushAction.process(FlushAction.java:85)
	at com.zerocracy.farm.reactive.FlushAction.exec(FlushAction.java:67)
	at com.zerocracy.farm.reactive.FlushAction.exec(FlushAction.java:35)
	at org.cactoos.func.FuncOf.lambda$new$3(FuncOf.java:88)
	at org.cactoos.func.FuncOf.apply(FuncOf.java:104)
	at org.cactoos.func.IoCheckedFunc.apply(IoCheckedFunc.java:66)
	at org.cactoos.func.UncheckedFunc.apply(UncheckedFunc.java:59)
	at org.cactoos.func.RunnableOf.run(RunnableOf.java:89)
	at com.jcabi.log.VerboseRunnable.run(VerboseRu...
```
