### ISSUE TITLE
Adding left and right trim text functionality on Cactoos

### ISSUE THREAD

**Issue by memoyil** [yegor256/cactoos#358]
I have researched the most common string operations and i saw that left and right trim operations are using very common. 

https://www.quora.com/What-are-the-most-commonly-used-string-and-array-functions-in-php

And doing like that we will add Stringutils trim functionalites to Cactoos.

https://commons.apache.org/proper/commons-lang/apidocs/org/apache/commons/lang3/StringUtils.html#stripEnd-java.lang.String-java.lang.String-

**Comment by 0crat** [comment]
I can't do it for technical reasons, I'm very sorry. If you don't know what to do, submit this error as a ticket [here](https://github.com/zerocracy/datum):

```
1.0-SNAPSHOT ${buildNumber} 2017-08-04T07:36:32
java.lang.IllegalStateException: java.lang.reflect.InvocationTargetException
	at com.zerocracy.farm.reactive.StkGroovy.process(StkGroovy.java:115)
	at com.zerocracy.farm.StkSafe.process(StkSafe.java:89)
	at com.zerocracy.farm.reactive.Brigade.process(Brigade.java:103)
	at com.zerocracy.farm.reactive.Brigade.process(Brigade.java:82)
	at com.zerocracy.farm.reactive.FlushAction.process(FlushAction.java:85)
	at com.zerocracy.farm.reactive.FlushAction.exec(FlushAction.java:67)
	at com.zerocracy.farm.reactive.FlushAction.exec(FlushAction.java:35)
	at org.cactoos.func.FuncOf.lambda$new$3(FuncOf.java:88)
	at org.cactoos.func.FuncOf.apply(FuncOf.java:104)
	at org.cactoos.func.IoCheckedFunc.apply(IoCheckedFunc.java:66)
	at org.cactoos.func.UncheckedFunc.apply(UncheckedFunc.java:59)
	at org.cactoos.func.RunnableOf.run(RunnableOf.java:89)
	at com.jcabi.log.VerboseRunnable.run(VerboseRunnable.java:197)
	at com.zerocracy.farm.reactive.RunnableWithTrigger.run(RunnableWithTrigger.java:52)
	at java....
```
