### ISSUE TITLE
Sub-ranges and a little more of sets

### ISSUE THREAD

**Issue by ixmanuel** [yegor256/cactoos#365]
### A little of subranges and derived ideas.

# Domain of symbols:
Closed:     ```"["```, ```"]"```, ```">="```, ```"<="```,
Open:       ```"("```, ```")"```, ```">"```, ```"<"```,
Range:      ```"..."```, ```","```, ```"-"```
Infinitum:  ```"x..."```,   ```"...y"```,   ```"_..."```,   ```"..._"```,   ```"_..._"```,   ```"..."```,   ```"-"```,  ```","```

# Some examples:
[x, y]	new RangeOf("[x...y]")
(x, y)	new RangeOf("(x...y)")
[x, y)	new RangeOf("[x...y)")
(x, -)	new RangeOf("(x..._)")
(x, -)	new RangeOf("(x...)")
[x, y)	new RangeOf("x...<y)")
(-, -)	new RangeOf(...)

# Applications:
```java
// The Count is 9 :)
new LengthOf(new RangeOf("2...10"))

// ipsum
new SubText(
    new TextOf("Lorem ipsum"),
    new RangeOf(">6...")
)

// i, p, s, u, m
new Subset(
    new ArrayOf(
        new TextOf("Lorem ipsum"),
	new Separator("")
    ),
    new RangeOf("7...")
)

// "2, 3, 4, 5"
new TextOf(
    new RangeOf("2...<6"),
    new Separator(", ")
)

// \ When(x=2) -> 3...Until the end of the world
new Subset(set, new RangeOf(x -> ">x..."))

// 7
new ItemAt<>(
    new Cycled<>(new RangeOf("1...10")),
    7
)

// "1 times 1 = 1" ... "1 times 10 = 10"
new Combination<>(
    new RangeOf("1...10"),
     // Java, could your function be designed like this?
    (n) {
        System.out.println(
          new FormattedText("1 times %d = %d", n, 1*n)
        );
    }
)

// Tick-tack-samsara, the endless circus of life
new ItemAt<>(
    // Java, could your procedure be designed like this?
    new Endless<>({
        System.out.println(
            new TextOf(new RangeOf("1...12"), new Separator("-")).asString()
        );
    })
)

// "Do you think life is a sequence?: [2, 3, ..., 10]"
new FormattedText(
    new DecocactusTpl("Do you think life is a sequence?: [%d...]"),
    new RangeOf("2...10")
)

// The intermediate road: 100-500
new ListOf<>(
  new Filtered<>(
    new ArrayOf<>(new NaturalNumbers(1, 20000)),
    new RangeOf("[100-500]")
  )
)

// That's life: 1, 2, 3, 5, 8, ... 12586269025
new ListOf<>(
  new Filtered<>(
    new RangeOf("1...50"),
    IsFibonacci::proposition
  )
)

// Acum, the origin of the suffering: 10
new Reduced<>(
    new RangeOf("1...4")
    0,
    (first, second) -> first + second
)
```

# These also apply to any iterable/set:
```java
new IsEmpty(new Range("1..1"))
new LowerLimit(new Range(">1..10"))
new UpperLimit(new Range("5..<10"))
new Reversed(new Range("1..10"))
new Union(new Range(), new Range(), ...) 
new Substraction(new Range(), new Range(), ...)
new Intersection(new Range(), new Range(), ...)
new Difference(new Range(), new Range(), ...)
```

**Comment by svendiedrichsen** [comment]
How about different ranges like IntegerRangeOf and CharacterRangeOf?

**Comment by ixmanuel** [comment]
@svendiedrichsen I like the idea of  CharacterRangeOf and  yes, initially I had: 
```java
// (2, 10]
new RangeOf(new Open(2), new Close(10))
// [2, ...)
new RangeOf(new Open(2), new Open())
```
but later I though it could be more clear the actual proposal although it is more work.
At the beginning I tried:
```java
// Closed
new RangeOf(2, 9); 
// Open-Closed
new RangeOf(">2", 9);
```
but I didn't see very complete and clear. I tried to avoid parsing.
Then I thought in regular expressions and "2..9" is a kind of, then I said, why not?

I like your idea for letters and using the idea of regex:
new Uppercased(new Range("a..z"))
:)

**Comment by svendiedrichsen** [comment]
I agree it looks nice but parsing strings can get messy easily quickly.

**Comment by svendiedrichsen** [comment]
I have made a first implementation of an Range using int boundaries. Please take a look at https://github.com/svendiedrichsen/cactoos-range.git

**Comment by ixmanuel** [comment]
It seems good, I like it the implementation, and these alternatives are like a group of Jazz playing :), One improvise then another one improvise too then there is a conflict and finally a nice play. What do you think if we harmonise both ideas.

I think the both proposals are good alternatives, but let me tell you that I got the adventure to propose a range like a pattern because for what I have observed this seems a little  anti-java-status-quo and that's why I only made the proposal instead of implement it.

**Comment by ixmanuel** [comment]
@svendiedrichsen 
It seems good, I like it the implementation, and these alternatives are like a group of Jazz playing :), One improvise then another one improvise too then there is a conflict and finally a nice play. What do you think if we harmonise both ideas.

I think the both proposals are good alternatives, but let me tell you that I got the adventure to propose a range like a pattern because for what I have observed this seems a little  anti-java-status-quo and that's why I only made the proposal instead of implement it.

**Comment by svendiedrichsen** [comment]
Feel free to clone and do your part of jazz solo. :) We can go on from there.

**Comment by ixmanuel** [comment]
:) hahaha. Let's do it.

**Comment by svendiedrichsen** [comment]
I have made some small refactorings and added support for unbound ranges and functionality for LocalDate ranges.

**Comment by ixmanuel** [comment]
@svendiedrichsen Forget my proposal I like yours but, I think it could be less verbose. Wdyt?
```java
final Range<Integer> range = new Range<>(
    new OpenBound(2),
    new ClosedBound(10)
 );

final Range<Integer> range = new Range<>(
    new OpenBound(2),
    new OpenBound()
 );
```

**Comment by svendiedrichsen** [comment]
@ixmanuel Essentially you are proposing a merge of Lower and Upper of the bounds. I don't have a problem with it. I'll do it.

**Comment by ixmanuel** [comment]
@svendiedrichsen, Yes, you're right:
```
final Range<Integer> range = new Range<>(
    new Bound.Exclusive(2),
    new Bound.Inclusive(10)
 );

final Range<Integer> range = new Range<>(
    new Bound.Exclusive(2),
    new Bound.Exclusive()
 );
```

but, in this way infinitum-open-ranges are not very clear. 

I think you should make a PR in order to get feedback. You already have it.

**Comment by svendiedrichsen** [comment]
The unbound value unfortunatly cannot be done like `Bound.Exclusive()`. The value would depend wether the `Bound` is used as lower or upper bound. How should this be handled?

**Comment by svendiedrichsen** [comment]
I think I found something for the unbound case.

**Comment by ixmanuel** [comment]
I think if we use open and closed there are not ambiguities, [See: Interval in math](https://en.wikipedia.org/wiki/Interval_(mathematics)).

So, we could have:

```java
new Range(new Open(2), new Closed(10))

new Range(new Open(), new Closed(10)
```

We have the positions of each Open and Closed interval and therefore we could identify if it s upper or lower.

**Comment by svendiedrichsen** [comment]
I have refactored the code. Now it looks like this:
```
final Range<Integer> range =
            new Range<>(
                new IntegerBound.Inclusive(3),
                new IntegerBound.Inclusive()
            );
```
```
final Range<LocalDate> range =
    new Range<>(
        new LocalDateBound.Inclusive(
            LocalDate.of(2012, Month.JULY, 3)
        ),
        new LocalDateBound.Inclusive(
            LocalDate.of(2012, Month.JULY, 5)
        )
);
```
@ixmanuel WDYT?

**Comment by ixmanuel** [comment]
@svendiedrichsen Shouldn't range returns an iterable?

**Comment by svendiedrichsen** [comment]
Do you mean that it should _be_ an Iterable?

**Comment by 0crat** [comment]
There is an unrecoverablefailure on my side. Please, submit it [here](https://github.com/zerocracy/datum):

```
java.lang.ClassCastException: org.glassfish.json.JsonObjectBuilderImpl$JsonObjectImpl cannot be cast to javax.json.JsonString
	at org.glassfish.json.JsonObjectBuilderImpl$JsonObjectImpl.getJsonString(JsonObjectBuilderImpl.java:252)
	at org.glassfish.json.JsonObjectBuilderImpl$JsonObjectImpl.getString(JsonObjectBuilderImpl.java:257)
	at com.zerocracy.radars.github.RbByLabel.react(RbByLabel.java:82)
	at com.zerocracy.radars.github.RbByActions.react(RbByActions.java:65)
	at com.zerocracy.radars.github.Rebound$Chain.react(Rebound.java:74)
	at com.zerocracy.radars.github.RbSafe.lambda$react$0(RbSafe.java:63)
	at org.cactoos.func.FuncWithFallback.apply(FuncWithFallback.java:299)
	at org.cactoos.func.IoCheckedFunc.apply(IoCheckedFunc.java:66)
	at com.zerocracy.radars.github.RbSafe.react(RbSafe.java:79)
	at com.zerocracy.radars.github.RbLogged.react(RbLogged.java:52)
	at com.zerocracy.radars.github.TkGithub.act(TkGithub.java:161)
	at org.takes.facets.fork.FkRegex$1.act(FkRegex.java:154)
	at...
```

**Comment by 0crat** [comment]
There is an unrecoverablefailure on my side. Please, submit it [here](https://github.com/zerocracy/datum):

```
java.lang.ClassCastException: org.glassfish.json.JsonObjectBuilderImpl$JsonObjectImpl cannot be cast to javax.json.JsonString
	at org.glassfish.json.JsonObjectBuilderImpl$JsonObjectImpl.getJsonString(JsonObjectBuilderImpl.java:252)
	at org.glassfish.json.JsonObjectBuilderImpl$JsonObjectImpl.getString(JsonObjectBuilderImpl.java:257)
	at com.zerocracy.radars.github.RbByLabel.react(RbByLabel.java:82)
	at com.zerocracy.radars.github.RbByActions.react(RbByActions.java:65)
	at com.zerocracy.radars.github.Rebound$Chain.react(Rebound.java:74)
	at com.zerocracy.radars.github.RbSafe.lambda$react$0(RbSafe.java:63)
	at org.cactoos.func.FuncWithFallback.apply(FuncWithFallback.java:299)
	at org.cactoos.func.IoCheckedFunc.apply(IoCheckedFunc.java:66)
	at com.zerocracy.radars.github.RbSafe.react(RbSafe.java:79)
	at com.zerocracy.radars.github.RbLogged.react(RbLogged.java:52)
	at com.zerocracy.radars.github.TkGithub.act(TkGithub.java:161)
	at org.takes.facets.fork.FkRegex$1.act(FkRegex.java:154)
	at...
```

**Comment by 0crat** [comment]
There is an unrecoverablefailure on my side. Please, submit it [here](https://github.com/zerocracy/datum):

```
java.lang.ClassCastException: org.glassfish.json.JsonObjectBuilderImpl$JsonObjectImpl cannot be cast to javax.json.JsonString
	at org.glassfish.json.JsonObjectBuilderImpl$JsonObjectImpl.getJsonString(JsonObjectBuilderImpl.java:252)
	at org.glassfish.json.JsonObjectBuilderImpl$JsonObjectImpl.getString(JsonObjectBuilderImpl.java:257)
	at com.zerocracy.radars.github.RbByLabel.react(RbByLabel.java:82)
	at com.zerocracy.radars.github.RbByActions.react(RbByActions.java:65)
	at com.zerocracy.radars.github.Rebound$Chain.react(Rebound.java:74)
	at com.zerocracy.radars.github.RbSafe.lambda$react$0(RbSafe.java:63)
	at org.cactoos.func.FuncWithFallback.apply(FuncWithFallback.java:299)
	at org.cactoos.func.IoCheckedFunc.apply(IoCheckedFunc.java:66)
	at com.zerocracy.radars.github.RbSafe.react(RbSafe.java:79)
	at com.zerocracy.radars.github.RbLogged.react(RbLogged.java:52)
	at com.zerocracy.radars.github.TkGithub.act(TkGithub.java:161)
	at org.takes.facets.fork.FkRegex$1.act(FkRegex.java:154)
	at...
```

**Comment by 0crat** [comment]
There is an unrecoverablefailure on my side. Please, submit it [here](https://github.com/zerocracy/datum):

```
java.lang.ClassCastException: org.glassfish.json.JsonObjectBuilderImpl$JsonObjectImpl cannot be cast to javax.json.JsonString
	at org.glassfish.json.JsonObjectBuilderImpl$JsonObjectImpl.getJsonString(JsonObjectBuilderImpl.java:252)
	at org.glassfish.json.JsonObjectBuilderImpl$JsonObjectImpl.getString(JsonObjectBuilderImpl.java:257)
	at com.zerocracy.radars.github.RbByLabel.react(RbByLabel.java:82)
	at com.zerocracy.radars.github.RbByActions.react(RbByActions.java:65)
	at com.zerocracy.radars.github.Rebound$Chain.react(Rebound.java:74)
	at com.zerocracy.radars.github.RbSafe.lambda$react$0(RbSafe.java:63)
	at org.cactoos.func.FuncWithFallback.apply(FuncWithFallback.java:299)
	at org.cactoos.func.IoCheckedFunc.apply(IoCheckedFunc.java:66)
	at com.zerocracy.radars.github.RbSafe.react(RbSafe.java:79)
	at com.zerocracy.radars.github.RbLogged.react(RbLogged.java:52)
	at com.zerocracy.radars.github.TkGithub.act(TkGithub.java:161)
	at org.takes.facets.fork.FkRegex$1.act(FkRegex.java:154)
	at...
```

**Comment by 0crat** [comment]
Oops! There is no order for job `gh:yegor256/cactoos#365`.

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/cactoos#365` was not in scope
