### ISSUE TITLE
RepeatedFunc wrongly throws exception

### ISSUE THREAD

**Issue by HDouss** [yegor256/cactoos#376]
I expect the following code to run without a problem :
```java
        new RepeatedFunc<>(
            input -> {return null;}, 2
        ).apply(true);
```
Instead I got an exception : `java.lang.IllegalArgumentException: Repeat counter is equal or less than zero: 2`
I don't expect `RepeatedFunc` to behave like `NoNull` implementations, and even if it is the case, the exception message is completely wrong.
The implementation of `RepeatedFunc.apply` should be fixed to check for invalid `this.times` values instead of a `null` result.

**Comment by yegor256** [comment]
@0crat in

**Comment by yegor256** [comment]
@0crat assign @ixmanuel

**Comment by yegor256** [comment]
@ixmanuel can you please fix this?

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/yegor256/cactoos/issues/376#issuecomment-320243417))

@yegor256 Job `gh:yegor256/cactoos#376` is in scope.

**Comment by 0crat** [comment]
+15 points just awarded to @hdouss, total is [+15](http://www.0crat.com/u/hdouss).

**Comment by 0crat** [comment]
> @0crat assign @ixmanuel  ([here](https://github.com/yegor256/cactoos/issues/376#issuecomment-320243475))

@yegor256 Job `gh:yegor256/cactoos#376` assigned to @ixmanuel, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)). @ixmanuel is not a member of this project yet, but can request to join. @ixmanuel check your [Zerocracy profile](http://www.0crat.com/u/ixmanuel) and follow the instructions.

**Comment by ixmanuel** [comment]
@yegor256 See https://github.com/yegor256/cactoos/pull/381

**Comment by 0crat** [comment]
There is an unrecoverablefailure on my side. Please, submit it [here](https://github.com/zerocracy/datum):

```
java.lang.ClassCastException: org.glassfish.json.JsonObjectBuilderImpl$JsonObjectImpl cannot be cast to javax.json.JsonString
	at org.glassfish.json.JsonObjectBuilderImpl$JsonObjectImpl.getJsonString(JsonObjectBuilderImpl.java:252)
	at org.glassfish.json.JsonObjectBuilderImpl$JsonObjectImpl.getString(JsonObjectBuilderImpl.java:257)
	at com.zerocracy.radars.github.RbByLabel.react(RbByLabel.java:82)
	at com.zerocracy.radars.github.RbByActions.react(RbByActions.java:65)
	at com.zerocracy.radars.github.Rebound$Chain.react(Rebound.java:74)
	at com.zerocracy.radars.github.RbSafe.lambda$react$0(RbSafe.java:63)
	at org.cactoos.func.FuncWithFallback.apply(FuncWithFallback.java:299)
	at org.cactoos.func.IoCheckedFunc.apply(IoCheckedFunc.java:66)
	at com.zerocracy.radars.github.RbSafe.react(RbSafe.java:79)
	at com.zerocracy.radars.github.RbLogged.react(RbLogged.java:52)
	at com.zerocracy.radars.github.TkGithub.act(TkGithub.java:161)
	at org.takes.facets.fork.FkRegex$1.act(FkRegex.java:154)
	at...
```

**Comment by 0crat** [comment]
There is an unrecoverablefailure on my side. Please, submit it [here](https://github.com/zerocracy/datum):

```
java.lang.ClassCastException: org.glassfish.json.JsonObjectBuilderImpl$JsonObjectImpl cannot be cast to javax.json.JsonString
	at org.glassfish.json.JsonObjectBuilderImpl$JsonObjectImpl.getJsonString(JsonObjectBuilderImpl.java:252)
	at org.glassfish.json.JsonObjectBuilderImpl$JsonObjectImpl.getString(JsonObjectBuilderImpl.java:257)
	at com.zerocracy.radars.github.RbByLabel.react(RbByLabel.java:82)
	at com.zerocracy.radars.github.RbByActions.react(RbByActions.java:65)
	at com.zerocracy.radars.github.Rebound$Chain.react(Rebound.java:74)
	at com.zerocracy.radars.github.RbSafe.lambda$react$0(RbSafe.java:63)
	at org.cactoos.func.FuncWithFallback.apply(FuncWithFallback.java:299)
	at org.cactoos.func.IoCheckedFunc.apply(IoCheckedFunc.java:66)
	at com.zerocracy.radars.github.RbSafe.react(RbSafe.java:79)
	at com.zerocracy.radars.github.RbLogged.react(RbLogged.java:52)
	at com.zerocracy.radars.github.TkGithub.act(TkGithub.java:161)
	at org.takes.facets.fork.FkRegex$1.act(FkRegex.java:154)
	at...
```

**Comment by 0crat** [comment]
There is an unrecoverablefailure on my side. Please, submit it [here](https://github.com/zerocracy/datum):

```
java.lang.ClassCastException: org.glassfish.json.JsonObjectBuilderImpl$JsonObjectImpl cannot be cast to javax.json.JsonString
	at org.glassfish.json.JsonObjectBuilderImpl$JsonObjectImpl.getJsonString(JsonObjectBuilderImpl.java:252)
	at org.glassfish.json.JsonObjectBuilderImpl$JsonObjectImpl.getString(JsonObjectBuilderImpl.java:257)
	at com.zerocracy.radars.github.RbByLabel.react(RbByLabel.java:82)
	at com.zerocracy.radars.github.RbByActions.react(RbByActions.java:65)
	at com.zerocracy.radars.github.Rebound$Chain.react(Rebound.java:74)
	at com.zerocracy.radars.github.RbSafe.lambda$react$0(RbSafe.java:63)
	at org.cactoos.func.FuncWithFallback.apply(FuncWithFallback.java:299)
	at org.cactoos.func.IoCheckedFunc.apply(IoCheckedFunc.java:66)
	at com.zerocracy.radars.github.RbSafe.react(RbSafe.java:79)
	at com.zerocracy.radars.github.RbLogged.react(RbLogged.java:52)
	at com.zerocracy.radars.github.TkGithub.act(TkGithub.java:161)
	at org.takes.facets.fork.FkRegex$1.act(FkRegex.java:154)
	at...
```

**Comment by 0crat** [comment]
There is an unrecoverablefailure on my side. Please, submit it [here](https://github.com/zerocracy/datum):

```
java.lang.ClassCastException: org.glassfish.json.JsonObjectBuilderImpl$JsonObjectImpl cannot be cast to javax.json.JsonString
	at org.glassfish.json.JsonObjectBuilderImpl$JsonObjectImpl.getJsonString(JsonObjectBuilderImpl.java:252)
	at org.glassfish.json.JsonObjectBuilderImpl$JsonObjectImpl.getString(JsonObjectBuilderImpl.java:257)
	at com.zerocracy.radars.github.RbByLabel.react(RbByLabel.java:82)
	at com.zerocracy.radars.github.RbByActions.react(RbByActions.java:65)
	at com.zerocracy.radars.github.Rebound$Chain.react(Rebound.java:74)
	at com.zerocracy.radars.github.RbSafe.lambda$react$0(RbSafe.java:63)
	at org.cactoos.func.FuncWithFallback.apply(FuncWithFallback.java:299)
	at org.cactoos.func.IoCheckedFunc.apply(IoCheckedFunc.java:66)
	at com.zerocracy.radars.github.RbSafe.react(RbSafe.java:79)
	at com.zerocracy.radars.github.RbLogged.react(RbLogged.java:52)
	at com.zerocracy.radars.github.TkGithub.act(TkGithub.java:161)
	at org.takes.facets.fork.FkRegex$1.act(FkRegex.java:154)
	at...
```

**Comment by 0crat** [comment]
@ixmanuel resigned from `gh:yegor256/cactoos#376`, please stop working.

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#376` assigned to @kkamkou, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by 0crat** [comment]
@kkamkou resigned from `gh:yegor256/cactoos#376`, please stop working.

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#376` assigned to @kkamkou, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by 0crat** [comment]
@kkamkou resigned from `gh:yegor256/cactoos#376`, please stop working.

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#376` assigned to @kkamkou, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by 0crat** [comment]
@kkamkou resigned from `gh:yegor256/cactoos#376`, please stop working.

**Comment by t-izbassar** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/yegor256/cactoos/issues/376#issuecomment-359945253))

@t-izbassar This is what I know about this job, as in [§32](http://datum.zerocracy.com/pages/policy.html#32):

  * The job [#376](https://github.com/yegor256/cactoos/issues/376) is in scope
  * The role is `DEV`
  * The job is assigned to @t-izbassar[/z](https://www.0crat.com/u/t-izbassar)
  * These users are banned: @kkamkou[/z](https://www.0crat.com/u/kkamkou): User was resigned from the ticket

**Comment by t-izbassar** [comment]
@HDouss you should close this issue as #381 is merged.
@yegor256 I think that issue should be assigned back to @ixmanuel as he finished implemantation
@0crat waiting

**Comment by 0crat** [comment]
Are you speaking to me or about me [here](https://github.com/yegor256/cactoos/issues/376#issuecomment-359946162) You must always start your message with my name if you want to address it to me, see [§1](http://datum.zerocracy.com/pages/policy.html#1).

**Comment by t-izbassar** [comment]
@0crat waiting

**Comment by 0crat** [comment]
> @0crat waiting ([here](https://github.com/yegor256/cactoos/issues/376#issuecomment-359946316))

@t-izbassar The impediment for [#376](https://github.com/yegor256/cactoos/issues/376) was registered successfully by @t-izbassar[/z](https://www.0crat.com/u/t-izbassar)

**Comment by ixmanuel** [comment]
@t-izbassar Is this error rising in the Ocract app? I can't see the full log and the lines that I can review are related with FuncWithFallback and IoCheckedFunc. These are not related with RepeatedFunc. The tests for RepatedFunc are running ok. So, does Ocrat needs a different kind of exception? because now, it is IllegalArgumentException.

**Comment by ixmanuel** [comment]
@HDouss could yo close this issue?

**Comment by HDouss** [comment]
@ixmanuel Thanks!

**Comment by 0crat** [comment]
Order was successfully finished: +30 points just awarded to @t-izbassar[/z](https://www.0crat.com/u/t-izbassar), total is [+0](https://www.0crat.com/u/t-izbassar)

**Comment by 0crat** [comment]
The job [#376](https://github.com/yegor256/cactoos/issues/376) is now out of scope
