### ISSUE TITLE
ItemAt has duplicate

### ISSUE THREAD

**Issue by Meerownymous** [yegor256/cactoos#377]
ItemAt currently exists in Iterable and in Iterator. It should be deleted from Iterable.

**Comment by memoyil** [comment]
@Meerownymous Iterable classes are being used to create Iterator objects. Therefore it is normal to have same name but they have different usage.

**Comment by Meerownymous** [comment]
It creates a scalar, not an iterable? It is completely duplicate code, I think...

**Comment by 0crat** [comment]
There is an unrecoverablefailure on my side. Please, submit it [here](https://github.com/zerocracy/datum):

```
java.lang.ClassCastException: org.glassfish.json.JsonObjectBuilderImpl$JsonObjectImpl cannot be cast to javax.json.JsonString
	at org.glassfish.json.JsonObjectBuilderImpl$JsonObjectImpl.getJsonString(JsonObjectBuilderImpl.java:252)
	at org.glassfish.json.JsonObjectBuilderImpl$JsonObjectImpl.getString(JsonObjectBuilderImpl.java:257)
	at com.zerocracy.radars.github.RbByLabel.react(RbByLabel.java:82)
	at com.zerocracy.radars.github.RbByActions.react(RbByActions.java:65)
	at com.zerocracy.radars.github.Rebound$Chain.react(Rebound.java:74)
	at com.zerocracy.radars.github.RbSafe.lambda$react$0(RbSafe.java:63)
	at org.cactoos.func.FuncWithFallback.apply(FuncWithFallback.java:299)
	at org.cactoos.func.IoCheckedFunc.apply(IoCheckedFunc.java:66)
	at com.zerocracy.radars.github.RbSafe.react(RbSafe.java:79)
	at com.zerocracy.radars.github.RbLogged.react(RbLogged.java:52)
	at com.zerocracy.radars.github.TkGithub.act(TkGithub.java:161)
	at org.takes.facets.fork.FkRegex$1.act(FkRegex.java:154)
	at...
```

**Comment by 0crat** [comment]
There is an unrecoverablefailure on my side. Please, submit it [here](https://github.com/zerocracy/datum):

```
java.lang.ClassCastException: org.glassfish.json.JsonObjectBuilderImpl$JsonObjectImpl cannot be cast to javax.json.JsonString
	at org.glassfish.json.JsonObjectBuilderImpl$JsonObjectImpl.getJsonString(JsonObjectBuilderImpl.java:252)
	at org.glassfish.json.JsonObjectBuilderImpl$JsonObjectImpl.getString(JsonObjectBuilderImpl.java:257)
	at com.zerocracy.radars.github.RbByLabel.react(RbByLabel.java:82)
	at com.zerocracy.radars.github.RbByActions.react(RbByActions.java:65)
	at com.zerocracy.radars.github.Rebound$Chain.react(Rebound.java:74)
	at com.zerocracy.radars.github.RbSafe.lambda$react$0(RbSafe.java:63)
	at org.cactoos.func.FuncWithFallback.apply(FuncWithFallback.java:299)
	at org.cactoos.func.IoCheckedFunc.apply(IoCheckedFunc.java:66)
	at com.zerocracy.radars.github.RbSafe.react(RbSafe.java:79)
	at com.zerocracy.radars.github.RbLogged.react(RbLogged.java:52)
	at com.zerocracy.radars.github.TkGithub.act(TkGithub.java:161)
	at org.takes.facets.fork.FkRegex$1.act(FkRegex.java:154)
	at...
```

**Comment by 0crat** [comment]
There is an unrecoverablefailure on my side. Please, submit it [here](https://github.com/zerocracy/datum):

```
java.lang.ClassCastException: org.glassfish.json.JsonObjectBuilderImpl$JsonObjectImpl cannot be cast to javax.json.JsonString
	at org.glassfish.json.JsonObjectBuilderImpl$JsonObjectImpl.getJsonString(JsonObjectBuilderImpl.java:252)
	at org.glassfish.json.JsonObjectBuilderImpl$JsonObjectImpl.getString(JsonObjectBuilderImpl.java:257)
	at com.zerocracy.radars.github.RbByLabel.react(RbByLabel.java:82)
	at com.zerocracy.radars.github.RbByActions.react(RbByActions.java:65)
	at com.zerocracy.radars.github.Rebound$Chain.react(Rebound.java:74)
	at com.zerocracy.radars.github.RbSafe.lambda$react$0(RbSafe.java:63)
	at org.cactoos.func.FuncWithFallback.apply(FuncWithFallback.java:299)
	at org.cactoos.func.IoCheckedFunc.apply(IoCheckedFunc.java:66)
	at com.zerocracy.radars.github.RbSafe.react(RbSafe.java:79)
	at com.zerocracy.radars.github.RbLogged.react(RbLogged.java:52)
	at com.zerocracy.radars.github.TkGithub.act(TkGithub.java:161)
	at org.takes.facets.fork.FkRegex$1.act(FkRegex.java:154)
	at...
```

**Comment by 0crat** [comment]
There is an unrecoverablefailure on my side. Please, submit it [here](https://github.com/zerocracy/datum):

```
java.lang.ClassCastException: org.glassfish.json.JsonObjectBuilderImpl$JsonObjectImpl cannot be cast to javax.json.JsonString
	at org.glassfish.json.JsonObjectBuilderImpl$JsonObjectImpl.getJsonString(JsonObjectBuilderImpl.java:252)
	at org.glassfish.json.JsonObjectBuilderImpl$JsonObjectImpl.getString(JsonObjectBuilderImpl.java:257)
	at com.zerocracy.radars.github.RbByLabel.react(RbByLabel.java:82)
	at com.zerocracy.radars.github.RbByActions.react(RbByActions.java:65)
	at com.zerocracy.radars.github.Rebound$Chain.react(Rebound.java:74)
	at com.zerocracy.radars.github.RbSafe.lambda$react$0(RbSafe.java:63)
	at org.cactoos.func.FuncWithFallback.apply(FuncWithFallback.java:299)
	at org.cactoos.func.IoCheckedFunc.apply(IoCheckedFunc.java:66)
	at com.zerocracy.radars.github.RbSafe.react(RbSafe.java:79)
	at com.zerocracy.radars.github.RbLogged.react(RbLogged.java:52)
	at com.zerocracy.radars.github.TkGithub.act(TkGithub.java:161)
	at org.takes.facets.fork.FkRegex$1.act(FkRegex.java:154)
	at...
```

**Comment by 0crat** [comment]
Job [#377](https://github.com/yegor256/cactoos/issues/377) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#377](https://github.com/yegor256/cactoos/issues/377) assigned to @nikialeksey[/z](https://www.0crat.com/u/nikialeksey). The budget is 30 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§8](http://datum.zerocracy.com/pages/policy.html#8) and [§9](http://datum.zerocracy.com/pages/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by nikialeksey** [comment]
@Meerownymous pull request was merged

**Comment by 0crat** [comment]
@nikialeksey[/z](https://www.0crat.com/u/nikialeksey) this job was assigned to you 5 days ago. It will be taken away from you soon, unless you close it, see [§8](http://datum.zerocracy.com/pages/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by Meerownymous** [comment]
Looks good! Solved

**Comment by 0crat** [comment]
Order was successfully finished: +30 points just awarded to @nikialeksey[/z](https://www.0crat.com/u/nikialeksey), total is [+75](https://www.0crat.com/u/nikialeksey)

**Comment by 0crat** [comment]
The job [#377](https://github.com/yegor256/cactoos/issues/377) is now out of scope
