### ISSUE TITLE
org.cactoos.collection.Skipped

### ISSUE THREAD

**Issue by yegor256** [yegor256/cactoos#416]
Let's create `org.cactoos.collection.Skipped` class, similar to `org.cactoos.iterable.Skipped`

**Comment by 0crat** [comment]
There is an unrecoverablefailure on my side. Please, submit it [here](https://github.com/zerocracy/datum):

```
java.lang.ClassCastException: org.glassfish.json.JsonObjectBuilderImpl$JsonObjectImpl cannot be cast to javax.json.JsonString
	at org.glassfish.json.JsonObjectBuilderImpl$JsonObjectImpl.getJsonString(JsonObjectBuilderImpl.java:252)
	at org.glassfish.json.JsonObjectBuilderImpl$JsonObjectImpl.getString(JsonObjectBuilderImpl.java:257)
	at com.zerocracy.radars.github.RbByLabel.react(RbByLabel.java:82)
	at com.zerocracy.radars.github.RbByActions.react(RbByActions.java:65)
	at com.zerocracy.radars.github.Rebound$Chain.react(Rebound.java:74)
	at com.zerocracy.radars.github.RbSafe.lambda$react$0(RbSafe.java:63)
	at org.cactoos.func.FuncWithFallback.apply(FuncWithFallback.java:299)
	at org.cactoos.func.IoCheckedFunc.apply(IoCheckedFunc.java:66)
	at com.zerocracy.radars.github.RbSafe.react(RbSafe.java:79)
	at com.zerocracy.radars.github.RbLogged.react(RbLogged.java:52)
	at com.zerocracy.radars.github.TkGithub.act(TkGithub.java:161)
	at org.takes.facets.fork.FkRegex$1.act(FkRegex.java:154)
	at...
```

**Comment by 0crat** [comment]
There is an unrecoverablefailure on my side. Please, submit it [here](https://github.com/zerocracy/datum):

```
java.lang.ClassCastException: org.glassfish.json.JsonObjectBuilderImpl$JsonObjectImpl cannot be cast to javax.json.JsonString
	at org.glassfish.json.JsonObjectBuilderImpl$JsonObjectImpl.getJsonString(JsonObjectBuilderImpl.java:252)
	at org.glassfish.json.JsonObjectBuilderImpl$JsonObjectImpl.getString(JsonObjectBuilderImpl.java:257)
	at com.zerocracy.radars.github.RbByLabel.react(RbByLabel.java:82)
	at com.zerocracy.radars.github.RbByActions.react(RbByActions.java:65)
	at com.zerocracy.radars.github.Rebound$Chain.react(Rebound.java:74)
	at com.zerocracy.radars.github.RbSafe.lambda$react$0(RbSafe.java:63)
	at org.cactoos.func.FuncWithFallback.apply(FuncWithFallback.java:299)
	at org.cactoos.func.IoCheckedFunc.apply(IoCheckedFunc.java:66)
	at com.zerocracy.radars.github.RbSafe.react(RbSafe.java:79)
	at com.zerocracy.radars.github.RbLogged.react(RbLogged.java:52)
	at com.zerocracy.radars.github.TkGithub.act(TkGithub.java:161)
	at org.takes.facets.fork.FkRegex$1.act(FkRegex.java:154)
	at...
```

**Comment by 0crat** [comment]
There is an unrecoverablefailure on my side. Please, submit it [here](https://github.com/zerocracy/datum):

```
java.lang.ClassCastException: org.glassfish.json.JsonObjectBuilderImpl$JsonObjectImpl cannot be cast to javax.json.JsonString
	at org.glassfish.json.JsonObjectBuilderImpl$JsonObjectImpl.getJsonString(JsonObjectBuilderImpl.java:252)
	at org.glassfish.json.JsonObjectBuilderImpl$JsonObjectImpl.getString(JsonObjectBuilderImpl.java:257)
	at com.zerocracy.radars.github.RbByLabel.react(RbByLabel.java:82)
	at com.zerocracy.radars.github.RbByActions.react(RbByActions.java:65)
	at com.zerocracy.radars.github.Rebound$Chain.react(Rebound.java:74)
	at com.zerocracy.radars.github.RbSafe.lambda$react$0(RbSafe.java:63)
	at org.cactoos.func.FuncWithFallback.apply(FuncWithFallback.java:299)
	at org.cactoos.func.IoCheckedFunc.apply(IoCheckedFunc.java:66)
	at com.zerocracy.radars.github.RbSafe.react(RbSafe.java:79)
	at com.zerocracy.radars.github.RbLogged.react(RbLogged.java:52)
	at com.zerocracy.radars.github.TkGithub.act(TkGithub.java:161)
	at org.takes.facets.fork.FkRegex$1.act(FkRegex.java:154)
	at...
```

**Comment by 0crat** [comment]
There is an unrecoverablefailure on my side. Please, submit it [here](https://github.com/zerocracy/datum):

```
java.lang.ClassCastException: org.glassfish.json.JsonObjectBuilderImpl$JsonObjectImpl cannot be cast to javax.json.JsonString
	at org.glassfish.json.JsonObjectBuilderImpl$JsonObjectImpl.getJsonString(JsonObjectBuilderImpl.java:252)
	at org.glassfish.json.JsonObjectBuilderImpl$JsonObjectImpl.getString(JsonObjectBuilderImpl.java:257)
	at com.zerocracy.radars.github.RbByLabel.react(RbByLabel.java:82)
	at com.zerocracy.radars.github.RbByActions.react(RbByActions.java:65)
	at com.zerocracy.radars.github.Rebound$Chain.react(Rebound.java:74)
	at com.zerocracy.radars.github.RbSafe.lambda$react$0(RbSafe.java:63)
	at org.cactoos.func.FuncWithFallback.apply(FuncWithFallback.java:299)
	at org.cactoos.func.IoCheckedFunc.apply(IoCheckedFunc.java:66)
	at com.zerocracy.radars.github.RbSafe.react(RbSafe.java:79)
	at com.zerocracy.radars.github.RbLogged.react(RbLogged.java:52)
	at com.zerocracy.radars.github.TkGithub.act(TkGithub.java:161)
	at org.takes.facets.fork.FkRegex$1.act(FkRegex.java:154)
	at...
```

**Comment by fabriciofx** [comment]
@yegor256 Could you be more specific? What kind of help do you need? The code submitted was not good enough? Why?

**Comment by yegor256** [comment]
@fabriciofx we don't have `org.cactoos.collection.Skipped` at all. What "code submitted" are you talking about?)

**Comment by fabriciofx** [comment]
@yegor256 I'm taking about [this code](https://github.com/cheparinV/cactoos/commit/44ae77a7e9ac36155ac905cd7e0ed4b4b51e426b).

**Comment by yegor256** [comment]
@fabriciofx but it's not in our repo. Feel free to submit a pull request.

**Comment by fabriciofx** [comment]
@yegor256 But this code is not mine. @cheparinV Could you submit a PR of [this code](https://github.com/cheparinV/cactoos/commit/44ae77a7e9ac36155ac905cd7e0ed4b4b51e426b)?

**Comment by 0crat** [comment]
Job [#416](https://github.com/yegor256/cactoos/issues/416) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://datum.zerocracy.com/pages/policy.html#29): +15 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256), total is [+9260](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
The job [#416](https://github.com/yegor256/cactoos/issues/416) assigned to @sharpler[/z](https://www.0crat.com/u/sharpler). The budget is 30 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§8](http://datum.zerocracy.com/pages/policy.html#8) and [§9](http://datum.zerocracy.com/pages/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by 0crat** [comment]
Order was successfully finished: +30 points just awarded to @sharpler[/z](https://www.0crat.com/u/sharpler), total is [+45](https://www.0crat.com/u/sharpler)

**Comment by 0crat** [comment]
The job [#416](https://github.com/yegor256/cactoos/issues/416) is now out of scope
