### ISSUE TITLE
SyncInput and SyncOutput

### ISSUE THREAD

**Issue by yegor256** [yegor256/cactoos#430]
Let's introduce them.

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/datum):

```
java.lang.IllegalArgumentException: issue #430 doesn't have an assignee, use hasAssignee()
	at com.jcabi.github.Issue$Smart.assignee_aroundBody24(Issue.java:254)
	at com.jcabi.github.Issue$Smart$AjcClosure25.run(Issue.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.jcabi.aspects.aj.MethodLogger.wrap(MethodLogger.java:213)
	at com.jcabi.aspects.aj.MethodLogger.ajc$inlineAccessMethod$com_jcabi_aspects_aj_MethodLogger$com_jcabi_aspects_aj_MethodLogger$wrap(MethodLogger.java:1)
	at com.jcabi.aspects.aj.MethodLogger.wrapClass(MethodLogger.java:140)
	at com.jcabi.github.Issue$Smart.assignee(Issue.java:253)
	at com.zerocracy.radars.github.RbOnAssign.react(RbOnAssign.java:44)
	at com.zerocracy.radars.github.RbByActions.react(RbByActions.java:65)
	at com.zerocracy.radars.github.Rebound$Chain.react(Rebound.java:74)
	at com.zerocracy.radars.github.RbSafe.lambda$react$0(RbSafe.java:66)
	at org.cactoos.func.FuncWithFallback.apply(FuncWithFallback.jav...
```

**Comment by yegor256** [comment]
@rultor release, tag is `0.18`

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#430` assigned to @yegor256, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by 0crat** [comment]
+15 points just awarded to @yegor256, total is [+3390](http://www.0crat.com/u/yegor256).

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#430` is now out of scope.

**Comment by 0crat** [comment]
+30 points just awarded to @yegor256, total is [+3420](http://www.0crat.com/u/yegor256).
