### ISSUE TITLE
Converting arrays in a ctor

### ISSUE THREAD

**Issue by ashtonhogan** [yegor256/cactoos#541]
I wasn't sure where the best place to ask this question would be.

What I need is to accept an `Object[]` as input in a secondary ctor and then save every object in its `Iterator` to a `List` of some sort.

The code looks somewhat like this:

```
    public Foo(final Iterator iterator) { //Iterator contains Object[] == JsonString[]
        while (iterator.hasNext()) {
            this.bars.add( //List should contain Bar elements constructed with JsonString values
                    new Bar(
                            (JsonString) iterator.next()
                    )
            );
        }
    }
```

I wanted to know what's the best cactoos way to go about this? (If there is one)

Otherwise, perhaps I can take this opportunity to request some feedback on how an ideal cactoos object would work in scenarios like these?

I could probably put a bunch of execution code in a `Scalar` in the ctor but I prefer to shy away from this practice...
  
@yegor256 I believe this issue deserves the "question" label

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/datum):

```
java.lang.OutOfMemoryError: unable to create new native thread
	at java.lang.Thread.start0(Native Method)
	at java.lang.Thread.start(Thread.java:717)
	at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:957)
	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1378)
	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:112)
	at com.zerocracy.farm.sync.Terminator.submit(Terminator.java:106)
	at com.zerocracy.farm.sync.SyncProject.acq(SyncProject.java:97)
	at com.zerocracy.farm.strict.StrictProject.acq(StrictProject.java:117)
	at com.zerocracy.farm.props.PropsProject.acq(PropsProject.java:78)
	at com.zerocracy.farm.footprint.FtProject.acq(FtProject.java:67)
	at com.zerocracy.farm.uplinked.UplinkedProject.lambda$acq$4(UplinkedProject.java:99)
	at org.cactoos.scalar.Ternary.value(Ternary.java:123)
	at org.cactoos.func.IoCheckedFunc.lambda$apply$0(IoCheckedFunc.java:60)
	at org.cactoos.func.IoCheckedBiFunc.app...
```

[1.0-SNAPSHOT](https://github.com/zerocracy/farm/tree/1.0-SNAPSHOT) /cc @yegor256

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by yegor256** [comment]
@ashtonhogan you need `Mapped`:

```
public Foo(iterator) {
  this.bars = new Mapped<>(...);
}
```

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#541` is not assigned, can't get start time

**Comment by 0crat** [comment]
Job [#541](https://github.com/yegor256/cactoos/issues/541) was not in scope

**Comment by yegor256** [comment]
@ashtonhogan StackOverflow is a better platform for questions, see 8586d83

**Comment by ashtonhogan** [comment]
@yegor256 I was looking for an article on www.yegor256.com that would be relevant but none of them really fit the bill
