### ISSUE TITLE
"Random" Exception when running unit tests - org.cactoos.iterable.SolidIterableTest

### ISSUE THREAD

**Issue by allanwsilva** [yegor256/cactoos#545]
I was running the default maven goals and every now and then the `test` goal was spitting out the following exception:

```
Tests run: 3, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.036 sec <<< FAILURE! - in org.cactoos.iterable.SolidIterableTest
worksInThreads(org.cactoos.iterable.SolidIterableTest)  Time elapsed: 0.035 sec  <<< ERROR!
java.io.UncheckedIOException: java.io.IOException: java.util.concurrent.ExecutionException: java.lang.NullPointerException
        at org.cactoos.func.UncheckedBiFunc.apply(UncheckedBiFunc.java:62)
        at org.cactoos.func.UncheckedFunc.apply(UncheckedFunc.java:59)
        at org.cactoos.scalar.UncheckedScalar.value(UncheckedScalar.java:59)
        at org.cactoos.RunsInThreads.matchesSafely(RunsInThreads.java:105)
        at org.cactoos.RunsInThreads.matchesSafely(RunsInThreads.java:47)
        at org.hamcrest.TypeSafeMatcher.matches(TypeSafeMatcher.java:65)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:12)
        at org.cactoos.iterable.SolidIterableTest.worksInThreads(SolidIterableTest.java:76)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.apache.maven.surefire.junitcore.pc.Scheduler$1.run(Scheduler.java:393)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: java.util.concurrent.ExecutionException: java.lang.NullPointerException
        at org.cactoos.func.IoCheckedBiFunc.apply(IoCheckedBiFunc.java:75)
        at org.cactoos.func.UncheckedBiFunc.apply(UncheckedBiFunc.java:60)
        ... 25 more
Caused by: java.util.concurrent.ExecutionException: java.lang.NullPointerException
        at java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.util.concurrent.FutureTask.get(FutureTask.java:192)
        at org.cactoos.scalar.And.lambda$null$0(And.java:132)
        at org.cactoos.scalar.And.value(And.java:167)
        at org.cactoos.scalar.And.value(And.java:60)
        at org.cactoos.scalar.UncheckedScalar.lambda$value$0(UncheckedScalar.java:58)
        at org.cactoos.func.UncheckedFunc.lambda$apply$0(UncheckedFunc.java:58)
        at org.cactoos.func.IoCheckedBiFunc.apply(IoCheckedBiFunc.java:66)
        ... 26 more
Caused by: java.lang.NullPointerException
        at org.cactoos.iterable.IterableEnvelope.iterator(IterableEnvelope.java:57)
        at org.cactoos.iterable.IterableEnvelope.iterator(IterableEnvelope.java:57)
        at org.cactoos.iterable.IterableEnvelope.iterator(IterableEnvelope.java:57)
        at org.cactoos.iterable.SolidIterableTest.lambda$worksInThreads$3(SolidIterableTest.java:80)
        at org.cactoos.RunsInThreads.lambda$matchesSafely$0(RunsInThreads.java:94)
        ... 4 more
```

Environment: 
Win10
JDK 8 (1.8.0_131)
Apache Maven 3.5.2

**Comment by 0crat** [comment]
[@yegor256](http://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by fabriciofx** [comment]
@allanws I've received these exceptions too (I've a similar environment). My guess it's something related to Windows 10...

**Comment by Zefick** [comment]
The problem is that `SolidIterable` actually is not thread-safe. Let's look at `IterableEnvelope.iterator` method:

    public final Iterator<X> iterator() {
        return this.iterable.value().iterator();
    }

The `value()` call actually synchronized for `SyncIterable`, but `iterable()` is not! So two different `StickyIterable`s can invoke this `iterable` method simultaneously. In case of `SolidIterable` it can cause a race condition in `StickyBiFunc.value()` so that it returns our `null`. Sometimes it happens on my computer, but 90% of times is not. That's why the `worksInThreads` test is weak. Furthermore, it may pass even for simple non-synchronized and non-sticky iterables. And it will do it even more often than for `SolidIterable`, presumably always.

I tried to swap `StickyIterable` and `SyncIterable` in the main constructor of `SolidIterable` but the test still sometimes fails.

**Comment by fabriciofx** [comment]
@yegor256 Could you check it? Maybe it could be one of the reasons of threads leak in 0crat...

**Comment by 0crat** [comment]
Job [#545](https://github.com/yegor256/cactoos/issues/545) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://datum.zerocracy.com/pages/policy.html#29): +15 points just awarded to [@allanws](http://www.0crat.com/u/allanws), total is [+105](http://www.0crat.com/u/allanws)

**Comment by 0crat** [comment]
Job [#545](https://github.com/yegor256/cactoos/issues/545) is already in scope

**Comment by 0crat** [comment]
The job [#545](https://github.com/yegor256/cactoos/issues/545) assigned to @rexim[/z](https://www.0crat.com/u/rexim). The budget is 30 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§8](http://datum.zerocracy.com/pages/policy.html#8) and [§9](http://datum.zerocracy.com/pages/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by rexim** [comment]
@yegor256 should be fixed by #577. Please close this issue.

**Comment by rexim** [comment]
@0crat waiting

**Comment by 0crat** [comment]
> @0crat waiting ([here](https://github.com/yegor256/cactoos/issues/545#issuecomment-360848347))

@rexim The impediment for [#545](https://github.com/yegor256/cactoos/issues/545) was registered successfully by @rexim[/z](https://www.0crat.com/u/rexim)

**Comment by svendiedrichsen** [comment]
@allanwsilva Please close this issue.

**Comment by allanwsilva** [comment]
Closing as this was fixed in #577

**Comment by 0crat** [comment]
Order was successfully finished: +30 points just awarded to @rexim[/z](https://www.0crat.com/u/rexim), total is [+15](https://www.0crat.com/u/rexim)

**Comment by 0crat** [comment]
The job [#545](https://github.com/yegor256/cactoos/issues/545) is now out of scope

**Comment by 0crat** [comment]
Job [#545](https://github.com/yegor256/cactoos/issues/545) was not in scope
