### ISSUE TITLE
Can't create ResourceOf by supplying Texts

### ISSUE THREAD

**Issue by aliceice** [yegor256/cactoos#558]
Currently we can only create `ResourceOf` by supplying CharSequences as the resource name and fallback (and subsequently the Func<CharSequence, Input> fallback function).

I think it would be better to also accept `Text` as a parameters, too.

Currently we need to explicityl call `Text.asString()` when we want to use them as parameters like this:

```
Text path = new TextOf("folders/in/classpath")
Text resource = new TextOf("resource-file.xsl")

new ResourceOf(
    new FormattedText(
       new TextOf("%s/my-specific-folder/%s"), path, resource
    ).asString() // here
);
```

Instead I think it'd be better to do it like this
```
Text path = new TextOf("folders/in/classpath")
Text resource = new TextOf("resource-file.xsl")

new ResourceOf(
    new FormattedText(
       new TextOf("%s/my-specific-folder/%s"), path, resource
    ) // no .asString() here
);
```

What do you think?

**Comment by 0crat** [comment]
@yegor256[/z](http://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/datum):

```
java.lang.OutOfMemoryError: unable to create new native thread
	at java.lang.Thread.start0(Native Method)
	at java.lang.Thread.start(Thread.java:717)
	at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:957)
	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1378)
	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:112)
	at com.zerocracy.farm.sync.Terminator.submit(Terminator.java:106)
	at com.zerocracy.farm.sync.SyncProject.acq(SyncProject.java:97)
	at com.zerocracy.farm.strict.StrictProject.acq(StrictProject.java:117)
	at com.zerocracy.farm.props.PropsProject.acq(PropsProject.java:78)
	at com.zerocracy.farm.footprint.FtProject.acq(FtProject.java:67)
	at com.zerocracy.farm.uplinked.UplinkedProject.lambda$acq$4(UplinkedProject.java:99)
	at org.cactoos.scalar.Ternary.value(Ternary.java:123)
	at org.cactoos.func.IoCheckedFunc.lambda$apply$0(IoCheckedFunc.java:60)
	at org.cactoos.func.IoCheckedBiFunc.app...
```

[1.0-SNAPSHOT](https://github.com/zerocracy/farm/tree/1.0-SNAPSHOT) /cc @yegor256

**Comment by 0crat** [comment]
Job [#558](https://github.com/yegor256/cactoos/issues/558) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#558](https://github.com/yegor256/cactoos/issues/558) assigned to @flslkxtc[/z](https://www.0crat.com/u/flslkxtc). The budget is 30 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§8](http://datum.zerocracy.com/pages/policy.html#8) and [§9](http://datum.zerocracy.com/pages/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by flslkxtc** [comment]
@yegor256 Pull request https://github.com/yegor256/cactoos/pull/562 is merged, this task is complete.

**Comment by yegor256** [comment]
@flslkxtc  thanks

**Comment by 0crat** [comment]
Order was successfully finished: +30 points just awarded to @flslkxtc[/z](https://www.0crat.com/u/flslkxtc), total is [+60](https://www.0crat.com/u/flslkxtc)

**Comment by 0crat** [comment]
The job [#558](https://github.com/yegor256/cactoos/issues/558) is now out of scope
